server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn_content?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    application:
      name: learn-content

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto



